#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using UnityEngine.Animations;
using System.Collections.Generic;
using System.IO;
using System.Linq;

public class PlayerAnimatorBuilder : EditorWindow
{
    private GameObject playerObject;
    private Animator animatorComponent;
    private Vector2 scrollPosition;

    // The editor-only builder window is defined in Assets/Animations/Editor/PlayerAnimatorBuilder.cs.
    // This runtime copy is kept for reference but does not register a duplicate menu item.
    public static void ShowWindow()
    {
        GetWindow<PlayerAnimatorBuilder>("Player Animation Builder");
    }

    private void OnGUI()
    {
        GUILayout.Label("Player Animation Builder", EditorStyles.boldLabel);
        GUILayout.Space(10);

        playerObject = (GameObject)EditorGUILayout.ObjectField("Player GameObject", playerObject, typeof(GameObject), true);

        if (playerObject != null)
        {
            animatorComponent = playerObject.GetComponentInChildren<Animator>();
            if (animatorComponent == null)
            {
                EditorGUILayout.HelpBox("No Animator component found on Player or its children.", MessageType.Warning);
            }
            else
            {
                EditorGUILayout.HelpBox("Animator found: " + animatorComponent.name, MessageType.Info);
            }
        }

        GUILayout.Space(20);
        if (GUILayout.Button("BUILD COMPLETE PLAYER ANIMATOR", GUILayout.Height(40)))
        {
            BuildPlayerAnimator();
        }
    }

    private void BuildPlayerAnimator()
    {
        if (playerObject == null)
        {
            EditorUtility.DisplayDialog("Error", "Select your Player GameObject in the Hierarchy first.", "OK");
            return;
        }

        animatorComponent = playerObject.GetComponentInChildren<Animator>();
        if (animatorComponent == null)
        {
            EditorUtility.DisplayDialog("Error", "No Animator component found on Player or its children.", "OK");
            return;
        }

        string animationsPath = "Assets/Animations";
        if (!AssetDatabase.IsValidFolder(animationsPath))
        {
            EditorUtility.DisplayDialog("Error", "Animations folder not found at " + animationsPath, "OK");
            return;
        }

        string animationsPathForFind = animationsPath;
        var animationClips = ScanForAnimationClips(animationsPathForFind);
        if (animationClips.Count == 0)
        {
            // Fallback: try to find and import FBX files directly
            EditorUtility.DisplayDialog("Warning", "No animation clips found via AssetDatabase. Trying to scan FBX files directly...", "OK");
            animationClips = ScanForFbxAnimationClips(animationsPathForFind);

            if (animationClips.Count == 0)
            {
                EditorUtility.DisplayDialog("Error", "No animation clips found in " + animationsPath + "\n\nMake sure:\n1. FBX files are imported in Unity\n2. Animation clips are extracted in the FBX import settings\n3. The files are in the correct folder: " + animationsPath, "OK");
                return;
            }
        }

        var categorized = CategorizeAnimations(animationClips);
        bool hasLocomotion = categorized.Locomotion.Count > 0;
        bool hasCombat = categorized.Combat.Count > 0;
        bool hasDefense = categorized.Defense.Count > 0;
        bool hasBow = categorized.Bow.Count > 0;
        bool hasLadder = categorized.Ladder.Count > 0;
        bool hasInteraction = categorized.Interaction.Count > 0;
        bool hasOther = categorized.Other.Count > 0;

        string controllerPath = Path.Combine(animationsPath, "PlayerAutoGenerated.controller");
        if (File.Exists(controllerPath))
        {
            AssetDatabase.DeleteAsset(controllerPath);
        }

        var controller = AnimatorController.CreateAnimatorControllerAtPath(controllerPath);
        var baseLayer = controller.layers[0];
        var stateMachine = baseLayer.stateMachine;

        // ChildAnimatorStateMachine is a struct, so we use the nullable form (ChildAnimatorStateMachine?)
        // to represent "this category doesn't exist" instead of comparing a struct to null directly.
        var stateMachines = new Dictionary<string, ChildAnimatorStateMachine>();

        ChildAnimatorStateMachine AddStateMachine(string name, ref Vector2 position)
        {
            var sm = stateMachine.AddStateMachine(name, position);
            stateMachines[name] = new ChildAnimatorStateMachine { stateMachine = sm, position = position };
            position.x += 300;
            return stateMachines[name];
        }

        Vector2 position = new Vector2(0, 0);
        ChildAnimatorStateMachine? locomotionSM = hasLocomotion ? (ChildAnimatorStateMachine?)AddStateMachine("LOCOMOTION", ref position) : null;
        ChildAnimatorStateMachine? combatSM = hasCombat ? (ChildAnimatorStateMachine?)AddStateMachine("COMBAT", ref position) : null;
        ChildAnimatorStateMachine? defenseSM = hasDefense ? (ChildAnimatorStateMachine?)AddStateMachine("DEFENSE", ref position) : null;
        ChildAnimatorStateMachine? bowSM = hasBow ? (ChildAnimatorStateMachine?)AddStateMachine("BOW", ref position) : null;
        ChildAnimatorStateMachine? ladderSM = hasLadder ? (ChildAnimatorStateMachine?)AddStateMachine("LADDER", ref position) : null;
        ChildAnimatorStateMachine? interactionSM = hasInteraction ? (ChildAnimatorStateMachine?)AddStateMachine("INTERACTION", ref position) : null;
        ChildAnimatorStateMachine? otherSM = hasOther ? (ChildAnimatorStateMachine?)AddStateMachine("OTHER", ref position) : null;

        AnimatorState locomotionEntryState = null;
        if (hasLocomotion)
        {
            locomotionEntryState = SetupLocomotionEntryState(stateMachine, categorized.Locomotion);
            SetupLocomotion(locomotionSM.Value, categorized.Locomotion);
        }

        if (hasCombat)
        {
            SetupCombat(combatSM.Value, categorized.Combat.First());
        }

        if (hasDefense)
        {
            SetupDefense(defenseSM.Value, categorized.Defense.First());
        }

        if (hasBow)
        {
            SetupCategoryStates(bowSM.Value, categorized.Bow, "BOW");
        }
        if (hasLadder)
        {
            SetupCategoryStates(ladderSM.Value, categorized.Ladder, "LADDER");
        }
        if (hasInteraction)
        {
            SetupCategoryStates(interactionSM.Value, categorized.Interaction, "INTERACTION");
        }
        if (hasOther)
        {
            SetupCategoryStates(otherSM.Value, categorized.Other, "OTHER");
        }

        SetupParameters(controller);

        if (!ControllerHasRequiredParameters(controller))
        {
            EditorUtility.DisplayDialog("Error", "Generated Animator Controller is missing required parameters.", "OK");
            return;
        }

        SetupTransitions(stateMachine, locomotionEntryState, locomotionSM, combatSM, defenseSM, bowSM, ladderSM, interactionSM, otherSM, categorized);

        AnimatorState defaultState = locomotionEntryState;

        bool ControllerHasRequiredParameters(AnimatorController ctrl)
        {
            var names = ctrl.parameters.Select(p => p.name).ToHashSet();
            return names.Contains("Speed") && names.Contains("Attack") && names.Contains("Roll") && names.Contains("Grounded");
        }

        if (defaultState == null)
        {
            defaultState = CreateBaseDefaultStateFromChild(stateMachine, combatSM)
                           ?? CreateBaseDefaultStateFromChild(stateMachine, defenseSM)
                           ?? CreateBaseDefaultStateFromChild(stateMachine, bowSM)
                           ?? CreateBaseDefaultStateFromChild(stateMachine, ladderSM)
                           ?? CreateBaseDefaultStateFromChild(stateMachine, interactionSM)
                           ?? CreateBaseDefaultStateFromChild(stateMachine, otherSM);
        }

        if (defaultState != null)
        {
            stateMachine.defaultState = defaultState;
        }

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        animatorComponent.runtimeAnimatorController = controller;

        EnsurePlayerAnimationDriver();

        EditorUtility.DisplayDialog("Success", "Player Animator built successfully!", "OK");
    }

    private List<AnimationClip> ScanForAnimationClips(string path)
    {
        var guids = AssetDatabase.FindAssets("t:AnimationClip", new[] { path });
        var clips = new List<AnimationClip>();
        foreach (var guid in guids)
        {
            string assetPath = AssetDatabase.GUIDToAssetPath(guid);
            var clip = AssetDatabase.LoadAssetAtPath<AnimationClip>(assetPath);
            if (clip != null)
            {
                clips.Add(clip);
            }
        }
        return clips;
    }

    private List<AnimationClip> ScanForFbxAnimationClips(string path)
    {
        var clips = new List<AnimationClip>();
        var fbxGuids = AssetDatabase.FindAssets("t:Model", new[] { path }); // FBX files import as Model assets

        foreach (var guid in fbxGuids)
        {
            string assetPath = AssetDatabase.GUIDToAssetPath(guid);

            // Try to load all sub-assets of type AnimationClip from this FBX
            var subAssets = AssetDatabase.LoadAllAssetRepresentationsAtPath(assetPath);
            foreach (var subAsset in subAssets)
            {
                var clip = subAsset as AnimationClip;
                if (clip != null)
                {
                    clips.Add(clip);
                }
            }

            // Alternative method: load the main asset and check for animation clips
            var model = AssetDatabase.LoadAssetAtPath<UnityEngine.Object>(assetPath);
            if (model != null)
            {
                // Get dependencies or sub-assets
                var dependencies = EditorUtility.CollectDependencies(new Object[] { model });
                foreach (var dep in dependencies)
                {
                    string depPath = AssetDatabase.GetAssetPath(dep);
                    if (depPath.EndsWith(".anim") || depPath.Contains("/Animations/"))
                    {
                        var depClip = AssetDatabase.LoadAssetAtPath<AnimationClip>(depPath);
                        if (depClip != null && !clips.Contains(depClip))
                        {
                            clips.Add(depClip);
                        }
                    }
                }
            }
        }

        return clips.Distinct().ToList();
    }

    private struct CategorizedAnimations
    {
        public List<AnimationClip> Locomotion;
        public List<AnimationClip> Combat;
        public List<AnimationClip> Defense;
        public List<AnimationClip> Bow;
        public List<AnimationClip> Ladder;
        public List<AnimationClip> Interaction;
        public List<AnimationClip> Other;
    }

    private CategorizedAnimations CategorizeAnimations(List<AnimationClip> clips)
    {
        var result = new CategorizedAnimations
        {
            Locomotion = new List<AnimationClip>(),
            Combat = new List<AnimationClip>(),
            Defense = new List<AnimationClip>(),
            Bow = new List<AnimationClip>(),
            Ladder = new List<AnimationClip>(),
            Interaction = new List<AnimationClip>(),
            Other = new List<AnimationClip>()
        };

        foreach (var clip in clips)
        {
            string name = clip.name.ToLower();
            bool categorized = false;

            if (name.Contains("idle") || name.Contains("walk") || name.Contains("run") || name.Contains("sprint") ||
                name.Contains("jog") || name.Contains("move") || name.Contains("locomotion") ||
                name.Contains("strafe") || name.Contains("backward") || name.Contains("forward"))
            {
                result.Locomotion.Add(clip);
                categorized = true;
            }
            else if (name.Contains("attack") || name.Contains("light") || name.Contains("heavy") ||
                     name.Contains("combo") || name.Contains("slash") || name.Contains("swing") ||
                     name.Contains("hit") || name.Contains("strike") || name.Contains("punch") ||
                     name.Contains("kick") || name.Contains("death") || name.Contains("die"))
            {
                result.Combat.Add(clip);
                categorized = true;
            }
            else if (name.Contains("roll") || name.Contains("dodge") || name.Contains("block") ||
                     name.Contains("guard") || name.Contains("parry") || name.Contains("hurt") ||
                     name.Contains("stagger") || name.Contains("knock") || name.Contains("evade"))
            {
                result.Defense.Add(clip);
                categorized = true;
            }
            else if (name.Contains("bow") || name.Contains("archer") || name.Contains("arrow") ||
                     name.Contains("shoot") || name.Contains("aim") || name.Contains("draw"))
            {
                result.Bow.Add(clip);
                categorized = true;
            }
            else if (name.Contains("ladder") || name.Contains("climb") || name.Contains("climbing"))
            {
                result.Ladder.Add(clip);
                categorized = true;
            }
            else if (name.Contains("interact") || name.Contains("pickup") || name.Contains("pick") ||
                     name.Contains("use") || name.Contains("open") || name.Contains("close") ||
                     name.Contains("push") || name.Contains("pull") || name.Contains("talk") ||
                     name.Contains("sit") || name.Contains("stand"))
            {
                result.Interaction.Add(clip);
                categorized = true;
            }

            if (!categorized)
            {
                result.Other.Add(clip);
            }
        }

        return result;
    }

    private void SetupLocomotion(ChildAnimatorStateMachine locomotionSM, List<AnimationClip> locomotionClips)
    {
        var sm = locomotionSM.stateMachine;
        Vector2 statePos = new Vector2(0, 0);

        if (locomotionClips.Count == 1)
        {
            var locomotionState = sm.AddState(locomotionClips[0].name, statePos);
            locomotionState.motion = locomotionClips[0];
            sm.defaultState = locomotionState;
            return;
        }

        // Prefer a serialized BlendTree, but some Unity versions/conditions
        // can produce invalid serialized motions. If BlendTree creation
        // appears unreliable, fall back to a single valid locomotion clip
        // (prefer an 'idle' clip if present) to avoid broken controller assets.
        // Disabled BlendTree usage due to missing BlendTree/BlendType in UnityEngine.Animations
        // if (TryCreateLocomotionBlendTreeState(sm, locomotionClips, statePos, out var locomotionBlendState))
        // {
        //     sm.defaultState = locomotionBlendState;
        //     return;
        // }

        // Choose an 'idle' clip as a safer default when available
        AnimationClip fallbackClip = locomotionClips.FirstOrDefault(c => c.name.ToLower().Contains("idle")) ?? locomotionClips[0];
        var fallbackState = sm.AddState(fallbackClip.name, statePos);
        fallbackState.motion = fallbackClip;
        sm.defaultState = fallbackState;
    }

    private AnimatorState SetupLocomotionEntryState(AnimatorStateMachine parentStateMachine, List<AnimationClip> locomotionClips)
    {
        Vector2 statePos = new Vector2(0, 0);

        if (locomotionClips.Count == 1)
        {
            var singleEntryState = parentStateMachine.AddState(locomotionClips[0].name, statePos);
            singleEntryState.motion = locomotionClips[0];
            return singleEntryState;
        }

        // if (TryCreateLocomotionBlendTreeState(parentStateMachine, locomotionClips, statePos, out var entryBlendState))
        // {
        //     return entryBlendState;
        // }

        var entryState = parentStateMachine.AddState(locomotionClips[0].name, statePos);
        entryState.motion = locomotionClips[0];
        return entryState;
    }

    private bool TryCreateLocomotionBlendTreeState(AnimatorStateMachine sm, List<AnimationClip> locomotionClips, Vector2 statePos, out AnimatorState blendState)
    {
        blendState = null;
        // Creating BlendTrees via script can sometimes lead to invalid
        // serialized motions in generated controller assets (m_Motion: {fileID: 0}).
        // For safety, we avoid creating blend trees here so controllers remain
        // composed of concrete AnimationClips only. Return false so callers
        // fall back to single-clip states.
        return false;
    }

    private void SetupCombat(ChildAnimatorStateMachine combatSM, AnimationClip combatClip)
    {
        var sm = combatSM.stateMachine;
        var state = sm.AddState(combatClip.name, new Vector2(0, 0));
        state.motion = combatClip;
    }

    private void SetupDefense(ChildAnimatorStateMachine defenseSM, AnimationClip defenseClip)
    {
        var sm = defenseSM.stateMachine;
        var state = sm.AddState(defenseClip.name, new Vector2(0, 0));
        state.motion = defenseClip;
    }

    private void SetupCategoryStates(ChildAnimatorStateMachine categorySM, List<AnimationClip> clips, string categoryName)
    {
        var sm = categorySM.stateMachine;
        Vector2 statePos = new Vector2(0, 0);
        float offsetY = 100f;

        for (int i = 0; i < clips.Count; i++)
        {
            var clip = clips[i];
            var state = sm.AddState(clip.name, new Vector2(0, statePos.y + i * offsetY));
            state.motion = clip;
        }
    }

    private void SetupParameters(AnimatorController controller)
    {
        controller.parameters = new AnimatorControllerParameter[0];

        var parameters = new List<AnimatorControllerParameter>
        {
            new AnimatorControllerParameter { name = "Speed", type = AnimatorControllerParameterType.Float },
            new AnimatorControllerParameter { name = "Attack", type = AnimatorControllerParameterType.Trigger },
            new AnimatorControllerParameter { name = "Roll", type = AnimatorControllerParameterType.Trigger },
            new AnimatorControllerParameter { name = "Grounded", type = AnimatorControllerParameterType.Bool }
        };

        controller.parameters = parameters.ToArray();
    }

    private void SetupTransitions(AnimatorStateMachine baseStateMachine,
                                  AnimatorState locomotionEntryState,
                                  ChildAnimatorStateMachine? locomotionSM,
                                  ChildAnimatorStateMachine? combatSM,
                                  ChildAnimatorStateMachine? defenseSM,
                                  ChildAnimatorStateMachine? bowSM,
                                  ChildAnimatorStateMachine? ladderSM,
                                  ChildAnimatorStateMachine? interactionSM,
                                  ChildAnimatorStateMachine? otherSM,
                                  CategorizedAnimations categorized)
    {
        AnimatorState locomotionState = locomotionEntryState;
        if (locomotionState == null && locomotionSM.HasValue && locomotionSM.Value.stateMachine.states.Length > 0)
        {
            locomotionState = locomotionSM.Value.stateMachine.states[0].state;
        }

        if (combatSM.HasValue && combatSM.Value.stateMachine.states.Length > 0)
        {
            var combatState = combatSM.Value.stateMachine.states[0].state;
            var anyToCombat = baseStateMachine.AddAnyStateTransition(combatState);
            anyToCombat.AddCondition(AnimatorConditionMode.If, 0f, "Attack");
            anyToCombat.hasExitTime = false;
            anyToCombat.exitTime = 0f;
            anyToCombat.duration = 0.1f;

            if (locomotionState != null)
            {
                var combatToLocomotion = combatState.AddTransition(locomotionState);
                combatToLocomotion.hasExitTime = true;
                combatToLocomotion.exitTime = 0.9f;
                combatToLocomotion.duration = 0.1f;
            }
        }

        if (defenseSM.HasValue && defenseSM.Value.stateMachine.states.Length > 0)
        {
            var defenseState = defenseSM.Value.stateMachine.states[0].state;
            var anyToDefense = baseStateMachine.AddAnyStateTransition(defenseState);
            anyToDefense.AddCondition(AnimatorConditionMode.If, 0f, "Roll");
            anyToDefense.hasExitTime = false;
            anyToDefense.exitTime = 0f;
            anyToDefense.duration = 0.1f;

            if (locomotionState != null)
            {
                var defenseToLocomotion = defenseState.AddTransition(locomotionState);
                defenseToLocomotion.hasExitTime = true;
                defenseToLocomotion.exitTime = 0.9f;
                defenseToLocomotion.duration = 0.1f;
            }
        }
    }

    private void EnsurePlayerAnimationDriver()
    {
        string driverPath = "Assets/Scripts/PlayerAnimationDriver.cs";
        string driverDirectory = Path.GetDirectoryName(driverPath);
        if (!AssetDatabase.IsValidFolder(driverDirectory))
        {
            AssetDatabase.CreateFolder("Assets", "Scripts");
        }

        if (!File.Exists(driverPath))
        {
            File.WriteAllText(driverPath, GetDriverScriptContent());
            AssetDatabase.ImportAsset(driverPath);
        }
        else
        {
            string existingContent = File.ReadAllText(driverPath);
            string newContent = GetDriverScriptContent();
            if (existingContent != newContent)
            {
                File.WriteAllText(driverPath, newContent);
                AssetDatabase.ImportAsset(driverPath);
            }
        }

        var driverTarget = animatorComponent != null ? animatorComponent.gameObject : playerObject;
        var driver = driverTarget.GetComponent<PlayerAnimationDriver>();
        if (driver == null)
        {
            driver = driverTarget.AddComponent<PlayerAnimationDriver>();
        }
    }

    private AnimatorState CreateBaseDefaultStateFromChild(AnimatorStateMachine baseStateMachine, ChildAnimatorStateMachine? childSM)
    {
        if (!childSM.HasValue || childSM.Value.stateMachine.states.Length == 0)
            return null;

        var childState = childSM.Value.stateMachine.states[0].state;
        var defaultState = baseStateMachine.AddState(childState.name + " Default", new Vector2(0, 0));
        defaultState.motion = childState.motion;
        return defaultState;
    }

    private string GetDriverScriptContent()
    {
        return @"using UnityEngine;

[RequireComponent(typeof(Animator))]
public class PlayerAnimationDriver : MonoBehaviour
{
    private Animator animator;

    private void Awake()
    {
        animator = GetComponent<Animator>();
    }

    public void PlayAttack()
    {
        if (animator != null)
        {
            animator.SetTrigger(""Attack"");
        }
    }

    public void PlayRoll()
    {
        if (animator != null)
        {
            animator.SetTrigger(""Roll"");
        }
    }

    public void SetSpeed(float speed)
    {
        if (animator != null)
        {
            animator.SetFloat(""Speed"", speed, 0.1f, Time.deltaTime);
        }
    }

    public void SetGrounded(bool grounded)
    {
        if (animator != null)
        {
            animator.SetBool(""Grounded"", grounded);
        }
    }

    public void PlayAnimation(string animationName)
    {
        if (animator != null && !string.IsNullOrEmpty(animationName))
        {
            animator.CrossFade(animationName, 0.1f);
        }
    }
}";
    }
}
#endif