#if UNITY_EDITOR
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using SoulsLike.Player;

namespace SoulsLike.EditorTools
{
    /// <summary>
    /// Rebuilds the Base Layer of PlayerAutoGenerated.controller from scratch:
    ///   - Locomotion state with a Speed-driven 1D blend tree (Idle/Walk/Run), set as default state
    ///   - Roll state wired to the "Roll" trigger, with ActionStateNotifier attached
    ///   - Attack state wired to the "Attack" trigger, with ActionStateNotifier attached
    ///   - Both Roll and Attack exit back to Locomotion after their clip finishes
    ///
    /// This edits the SAME controller asset (same GUID) so the reference already
    /// sitting on the Player GameObject in the scene keeps working - you don't
    /// need to reassign anything.
    ///
    /// NOTE: There's no dedicated Roll/dodge clip in the DoubleL pack that shipped
    /// with this project. This script uses 1Hand_Up_Crouch_F_InPlace as a stand-in
    /// so Roll is at least visually distinct and functionally correct (fires,
    /// blocks input for its duration, exits cleanly). Swap ROLL_CLIP_NAME below
    /// for a real roll animation when you have one.
    /// </summary>
    public static class PlayerAnimatorRepair
    {
        private const string ControllerPath = "Assets/Animations/PlayerAutoGenerated.controller";
        private const string ClipFolder = "Assets/Animations/";

        private const string IDLE_CLIP_NAME = "1Hand_Up_Stand_Idle_A_2";
        private const string WALK_CLIP_NAME = "1Hand_Up_Walk_A_F_InPlace";
        private const string RUN_CLIP_NAME = "1Hand_Up_Run_A_F_InPlace";
        private const string ATTACK_CLIP_NAME = "1Hand_Up_Attack_A_1_InPlace";
        private const string ROLL_CLIP_NAME = "1Hand_Up_Crouch_F_InPlace"; // TODO: replace with a real roll clip

        [MenuItem("Tools/Souls-Like Horror/Repair Player Animator Controller")]
        public static void Repair()
        {
            var controller = AssetDatabase.LoadAssetAtPath<AnimatorController>(ControllerPath);
            if (controller == null)
            {
                EditorUtility.DisplayDialog("Error", $"Could not find controller at {ControllerPath}", "OK");
                return;
            }

            AnimationClip idleClip = LoadClip(IDLE_CLIP_NAME);
            AnimationClip walkClip = LoadClip(WALK_CLIP_NAME);
            AnimationClip runClip = LoadClip(RUN_CLIP_NAME);
            AnimationClip attackClip = LoadClip(ATTACK_CLIP_NAME);
            AnimationClip rollClip = LoadClip(ROLL_CLIP_NAME);

            if (idleClip == null || walkClip == null || runClip == null || attackClip == null || rollClip == null)
            {
                EditorUtility.DisplayDialog("Error",
                    "One or more source clips couldn't be found under " + ClipFolder +
                    ". Check the *_CLIP_NAME constants match your actual file names.", "OK");
                return;
            }

            // Ensure the parameters our gameplay code actually uses exist.
            EnsureParameter(controller, "Speed", AnimatorControllerParameterType.Float);
            EnsureParameter(controller, "Attack", AnimatorControllerParameterType.Trigger);
            EnsureParameter(controller, "Roll", AnimatorControllerParameterType.Trigger);
            EnsureParameter(controller, "Grounded", AnimatorControllerParameterType.Bool);

            // Wipe the Base Layer's state machine and rebuild it clean.
            AnimatorControllerLayer[] layers = controller.layers;
            AnimatorControllerLayer baseLayer = layers[0];
            AnimatorStateMachine sm = new AnimatorStateMachine
            {
                name = "Base Layer",
                hideFlags = HideFlags.HideInHierarchy
            };
            AssetDatabase.AddObjectToAsset(sm, controller);
            baseLayer.stateMachine = sm;
            layers[0] = baseLayer;
            controller.layers = layers;

            // ---------- Locomotion (Idle/Walk/Run blend tree) ----------
            BlendTree blendTree = new BlendTree
            {
                name = "Locomotion",
                blendType = BlendTreeType.Simple1D,
                blendParameter = "Speed",
                useAutomaticThresholds = false
            };
            AssetDatabase.AddObjectToAsset(blendTree, controller);
            blendTree.AddChild(idleClip, 0f);
            blendTree.AddChild(walkClip, 2.2f);   // matches PlayerController.walkSpeed
            blendTree.AddChild(runClip, 5.2f);    // matches PlayerController.runSpeed

            AnimatorState locomotionState = sm.AddState("Locomotion");
            locomotionState.motion = blendTree;
            locomotionState.writeDefaultValues = true;
            sm.defaultState = locomotionState;

            // ---------- Roll ----------
            AnimatorState rollState = sm.AddState("Roll");
            rollState.motion = rollClip;
            rollState.writeDefaultValues = true;
            var rollNotifier = rollState.AddStateMachineBehaviour<ActionStateNotifier>();
            rollNotifier.exitProgress = 1f;

            AnimatorStateTransition anyToRoll = sm.AddAnyStateTransition(rollState);
            anyToRoll.AddCondition(AnimatorConditionMode.If, 0f, "Roll");
            anyToRoll.hasExitTime = false;
            anyToRoll.duration = 0.05f;
            anyToRoll.canTransitionToSelf = false;

            AnimatorStateTransition rollToLocomotion = rollState.AddTransition(locomotionState);
            rollToLocomotion.hasExitTime = true;
            rollToLocomotion.exitTime = 0.85f; // matches ActionStateNotifier's comment / exitProgress = 1
            rollToLocomotion.duration = 0.15f;
            rollToLocomotion.hasFixedDuration = true;

            // ---------- Attack ----------
            AnimatorState attackState = sm.AddState("Attack");
            attackState.motion = attackClip;
            attackState.writeDefaultValues = true;
            var attackNotifier = attackState.AddStateMachineBehaviour<ActionStateNotifier>();
            attackNotifier.exitProgress = 1f;

            AnimatorStateTransition anyToAttack = sm.AddAnyStateTransition(attackState);
            anyToAttack.AddCondition(AnimatorConditionMode.If, 0f, "Attack");
            anyToAttack.hasExitTime = false;
            anyToAttack.duration = 0.05f;
            anyToAttack.canTransitionToSelf = false;

            AnimatorStateTransition attackToLocomotion = attackState.AddTransition(locomotionState);
            attackToLocomotion.hasExitTime = true;
            attackToLocomotion.exitTime = 0.85f;
            attackToLocomotion.duration = 0.15f;
            attackToLocomotion.hasFixedDuration = true;

            EditorUtility.SetDirty(controller);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            EditorUtility.DisplayDialog("Done",
                "PlayerAutoGenerated.controller rebuilt:\n" +
                "- Locomotion blend tree (Idle/Walk/Run) is now the default state\n" +
                "- Roll and Attack are wired to their triggers\n" +
                "- ActionStateNotifier is attached to both so PlayerController.State unlocks correctly\n\n" +
                "Remember: Roll is using a placeholder clip (" + ROLL_CLIP_NAME + ") until you have a real roll animation.",
                "OK");
        }

        private static AnimationClip LoadClip(string clipName)
        {
            string path = ClipFolder + clipName + ".fbx";
            Object[] assets = AssetDatabase.LoadAllAssetsAtPath(path);
            foreach (Object obj in assets)
            {
                if (obj is AnimationClip clip && !clip.name.StartsWith("__preview__"))
                    return clip;
            }
            return null;
        }

        private static void EnsureParameter(AnimatorController controller, string name, AnimatorControllerParameterType type)
        {
            foreach (var p in controller.parameters)
            {
                if (p.name == name && p.type == type) return;
            }
            controller.AddParameter(name, type);
        }
    }
}
#endif